import bedrock from "./bedrockService.js";

const ai = bedrock;

export const runCriticPass = async (generatedContent) => {
  console.log("Stage 3: Running 'The Critic' for final polish...");

  const prompt = `
You are a meticulous Content Quality Critic. I have a JSON object generated by other AI models representing a lecture study guide.
Your task is to review and polising the content to ensure it is PERFECT.

Content to Review:
${JSON.stringify(generatedContent)}

Review Rules:
1. ARCHITECTURAL CODE REVIEW: You are a Senior Code Reviewer. Check all "code" fields. If the code is messy, poorly indented, or buggy, rewrite it into a clean, professional, and well-commented snippet, but DO NOT add logic or examples not mentioned in the transcript.
2. NO HALLUCINATION: If a section discusses code but the "code" field is empty, ONLY move exact code snippets mentioned in the description to the "code" field. Do NOT derive or invent missing code examples on your own.
3. LOGIC POLISH: Ensure every code block is functional and logical. Fix mismatched brackets or syntax errors immediately.
4. TEXT-CODE SEPARATION: If you see code snippets inside the "description" field, move them to the "code" field.
5. JSON INTEGRITY: Output ONLY the final, polished JSON. No other text.

Return ONLY the polished JSON object. No conversational text.
`;

  try {
    const response = await ai.chat.completions.create({
      model: "llama-3.3-70b-versatile",
      messages: [
        {
          role: "user",
          content: prompt
        }
      ],
      temperature: 0.2, // Low temperature for high precision
      response_format: { type: "json_object" }
    });

    const content = response.choices[0].message.content;
    const jsonMatch = content.match(/\{[\s\S]*\}/);
    return JSON.parse(jsonMatch[0]);
  } catch (error) {
    console.error("Critic pass error:", error);
    return generatedContent; // Return original if critic fails
  }
};
